# Generated by Django 4.2 on 2023-04-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopaterno', models.CharField(max_length=30)),
                ('apellidomaterno', models.CharField(max_length=30)),
                ('rol_estudiante', models.CharField(choices=[('JF', 'Jefe de Grupo'), ('SJ', 'Sub Jefe de Grupo'), ('OR', 'Ordinario')], default='JF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estatus', models.BooleanField()),
            ],
        ),
    ]
